# Generated by Django 6.0.3 on 2026-06-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'knowledge categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=300, unique=True)),
                ('answer', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated search terms')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='knowledge.knowledgecategory')),
            ],
            options={
                'ordering': ('category__name', 'question'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(db_index=True, max_length=300)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='knowledge.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('strategy', models.CharField(db_index=True, default='none', max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('used_fallback', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='knowledge.knowledgebase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['category', 'is_active', 'difficulty'], name='knowledge_k_categor_e55aae_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesynonym',
            constraint=models.UniqueConstraint(fields=('entry', 'phrase'), name='unique_entry_synonym'),
        ),
    ]
